# Working with OpenINTEL data in pandas/pyarrow

Note that pandas is sufficient for smaller computation loads. OpenINTEL data can be large, and pandas might not be suitable.
Other tools that we have available at DACS include a Spark based compute cluster, and clickhouseDB.

In [1]:
import pandas as pd
import requests
import io

# You also need to have the package 'pyarrow' installed!

In [2]:
# OpenINTEL open data URL, full directory available at: https://openintel.nl/download/
openintel_url = 'https://object.openintel.nl/openintel-public/fdns/basis=toplist/source=tranco/year=2023/month=01/day=01/part-00000-30d969f7-2b36-4163-bb1f-9b641a49e6eb-c000-3af237f7-ff6d-4793-9fdd-44462dc46f4c.gz.parquet'

In [3]:
# Download the file into memory
response = requests.get(openintel_url)
response.raise_for_status()  # Raise an error if the download fails

In [4]:
# Read the parquet file into a DataFrame
df = pd.read_parquet(io.BytesIO(response.content), engine="pyarrow")
# print(df.columns)
# Display the first few rows
print(df.columns)
# print(df.head(2))

Index(['query_type', 'query_name', 'response_type', 'response_name',
       'response_ttl', 'timestamp', 'rtt', 'worker_id', 'status_code',
       'ad_flag', 'section', 'ip4_address', 'ip6_address', 'country', 'as',
       'as_full', 'ip_prefix', 'cname_name', 'dname_name', 'mx_address',
       'mx_preference', 'ns_address', 'txt_text', 'ds_key_tag', 'ds_algorithm',
       'ds_digest_type', 'ds_digest', 'dnskey_flags', 'dnskey_protocol',
       'dnskey_algorithm', 'dnskey_pk_rsa_n', 'dnskey_pk_rsa_e',
       'dnskey_pk_rsa_bitsize', 'dnskey_pk_eccgost_x', 'dnskey_pk_eccgost_y',
       'dnskey_pk_dsa_t', 'dnskey_pk_dsa_q', 'dnskey_pk_dsa_p',
       'dnskey_pk_dsa_g', 'dnskey_pk_dsa_y', 'dnskey_pk_eddsa_a',
       'dnskey_pk_wire', 'nsec_next_domain_name', 'nsec_owner_rrset_types',
       'nsec3_hash_algorithm', 'nsec3_flags', 'nsec3_iterations', 'nsec3_salt',
       'nsec3_next_domain_name_hash', 'nsec3_owner_rrset_types',
       'nsec3param_hash_algorithm', 'nsec3param_flags',
       'nsec3param_iterations', 'nsec3param_salt', 'spf_text', 'soa_mname',
       'soa_rname', 'soa_serial', 'soa_refresh', 'soa_retry', 'soa_expire',
       'soa_minimum', 'rrsig_type_covered', 'rrsig_algorithm', 'rrsig_labels',
       'rrsig_original_ttl', 'rrsig_signature_inception',
       'rrsig_signature_expiration', 'rrsig_key_tag', 'rrsig_signer_name',
       'rrsig_signature', 'cds_key_tag', 'cds_algorithm', 'cds_digest_type',
       'cds_digest', 'cdnskey_flags', 'cdnskey_protocol', 'cdnskey_algorithm',
       'cdnskey_pk_rsa_n', 'cdnskey_pk_rsa_e', 'cdnskey_pk_rsa_bitsize',
       'cdnskey_pk_eccgost_x', 'cdnskey_pk_eccgost_y', 'cdnskey_pk_dsa_t',
       'cdnskey_pk_dsa_q', 'cdnskey_pk_dsa_p', 'cdnskey_pk_dsa_g',
       'cdnskey_pk_dsa_y', 'cdnskey_pk_eddsa_a', 'cdnskey_pk_wire',
       'caa_flags', 'caa_tag', 'caa_value', 'tlsa_usage', 'tlsa_selector',
       'tlsa_matchtype', 'tlsa_certdata', 'ptr_name'],
      dtype='object')

In [55]:
# Show all columns when printing DataFrames
pd.set_option('display.max_columns', None)

# Optionally show more rows too (if needed)
pd.set_option('display.max_rows', 100)

# Query by cname for cloudflare
cname_records = df[(df["response_type"] == "CNAME") & (df["response_name"].str.startswith('cloudflare', na=False)) 
                & (df["cname_name"].str.endswith('cloudflare.net.', na=False))]

# cname for imperva is incapdns.net
# cname_records = df[(df["response_type"] == "CNAME") 
#                 & (df["cname_name"].str.endswith('incapdns.net.', na=False))]

# cname for Akamai is akamai.net
# cname_records = df[(df["response_type"] == "CNAME") 
#                 & (df["cname_name"].str.endswith('akamai.net.', na=False))]

# cname for Ultraddos (Vercara) is ultradns.net
# cname_records = df[(df["response_type"] == "CNAME") 
#                 & (df["cname_name"].str.contains('ultradns', na=False))]

cname_records
# print(f"Len of unique number of domains {len(cname_records['query_name'].unique())}")

,query_type,query_name,response_type,response_name,response_ttl,timestamp,rtt,worker_id,status_code,ad_flag,section,ip4_address,ip6_address,country,as,as_full,ip_prefix,cname_name,dname_name,mx_address,mx_preference,ns_address,txt_text,ds_key_tag,ds_algorithm,ds_digest_type,ds_digest,dnskey_flags,dnskey_protocol,dnskey_algorithm,dnskey_pk_rsa_n,dnskey_pk_rsa_e,dnskey_pk_rsa_bitsize,dnskey_pk_eccgost_x,dnskey_pk_eccgost_y,dnskey_pk_dsa_t,dnskey_pk_dsa_q,dnskey_pk_dsa_p,dnskey_pk_dsa_g,dnskey_pk_dsa_y,dnskey_pk_eddsa_a,dnskey_pk_wire,nsec_next_domain_name,nsec_owner_rrset_types,nsec3_hash_algorithm,nsec3_flags,nsec3_iterations,nsec3_salt,nsec3_next_domain_name_hash,nsec3_owner_rrset_types,nsec3param_hash_algorithm,nsec3param_flags,nsec3param_iterations,nsec3param_salt,spf_text,soa_mname,soa_rname,soa_serial,soa_refresh,soa_retry,soa_expire,soa_minimum,rrsig_type_covered,rrsig_algorithm,rrsig_labels,rrsig_original_ttl,rrsig_signature_inception,rrsig_signature_expiration,rrsig_key_tag,rrsig_signer_name,rrsig_signature,cds_key_tag,cds_algorithm,cds_digest_type,cds_digest,cdnskey_flags,cdnskey_protocol,cdnskey_algorithm,cdnskey_pk_rsa_n,cdnskey_pk_rsa_e,cdnskey_pk_rsa_bitsize,cdnskey_pk_eccgost_x,cdnskey_pk_eccgost_y,cdnskey_pk_dsa_t,cdnskey_pk_dsa_q,cdnskey_pk_dsa_p,cdnskey_pk_dsa_g,cdnskey_pk_dsa_y,cdnskey_pk_eddsa_a,cdnskey_pk_wire,caa_flags,caa_tag,caa_value,tlsa_usage,tlsa_selector,tlsa_matchtype,tlsa_certdata,ptr_name
343855,A,www.yamana.com.,CNAME,cloudflare.cdn.web.prd.q4inc.com.,60.0,1672537041000,0.048344,1582299107,0,0,ans,None,None,None,None,None,None,cloudflare.cdn.web.prd.q4inc.com.cdn.cloudflar...,None,None,NaN,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,NaN,NaN,NaN,None,None,None,NaN,NaN,NaN,None,None,None,None,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,NaN,None,None,NaN,NaN,NaN,None,None
343863,AAAA,www.yamana.com.,CNAME,cloudflare.cdn.web.prd.q4inc.com.,60.0,1672537041000,0.000202,1582299107,0,0,ans,None,None,None,None,None,None,cloudflare.cdn.web.prd.q4inc.com.cdn.cloudflar...,None,None,NaN,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,NaN,NaN,NaN,None,None,None,NaN,NaN,NaN,None,None,None,None,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,NaN,None,None,NaN,NaN,NaN,None,None
469262,A,www.farmershomefurniture.com.,CNAME,cloudflare.microdinc.com.,600.0,1672536800000,0.047681,1582299107,0,0,ans,None,None,None,None,None,None,cloudflare.microdinc.com.cdn.cloudflare.net.,None,None,NaN,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,NaN,NaN,NaN,None,None,None,NaN,NaN,NaN,None,None,None,None,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,NaN,None,None,NaN,NaN,NaN,None,None
469267,AAAA,www.farmershomefurniture.com.,CNAME,cloudflare.microdinc.com.,600.0,1672536800000,0.005499,1582299107,0,0,ans,None,None,None,None,None,None,cloudflare.microdinc.com.cdn.cloudflare.net.,None,None,NaN,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,NaN,NaN,NaN,None,None,None,NaN,NaN,NaN,None,None,None,None,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,NaN,None,None,NaN,NaN,NaN,None,None
485383,A,www.penskeautomotive.com.,CNAME,cloudflare.cdn.web.prd.q4inc.com.,60.0,1672536547000,0.060590,1582299107,0,0,ans,None,None,None,None,None,None,cloudflare.cdn.web.prd.q4inc.com.cdn.cloudflar...,None,None,NaN,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,NaN,NaN,NaN,None,None,None,NaN,NaN,NaN,None,None,None,None,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,NaN,None,None,NaN,NaN,NaN,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12981936,AAAA,www.noblecorp.com.,CNAME,cloudflare.cdn.web.prd.q4inc.com.,60.0,1672534043000,0.000294,1582299107,0,0,ans,None,None,None,None,None,None,cloudflare.cdn.web.prd.q4inc.com.cdn.cloudflar...,None,None,NaN,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,NaN,NaN,NaN,None,None,None,NaN,NaN,NaN,None,None,None,None,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,NaN,None,None,NaN,NaN,NaN,None,None
13057621,A,www.enproindustries.com.,CNAME,cloudflare.cdn.web.prd.q4inc.com.,60.0,1672534258000,0.126836,1582299107,0,0,ans,None,None,None,None,None,None,cloudflare.cdn.web.prd.q4inc.com.cdn.cloudflar...,None,None,NaN,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,NaN,NaN,NaN,None,None,None,NaN,NaN,NaN,None,None,None,None,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,NaN,None,None,NaN,NaN,NaN,None,None
13057629,AAAA,www.enproindustries.com.,CNAME,cloudflare.cdn.web.prd.q4inc.com.,60.0,1672534258000,0.000110,1582299107,0,0,ans,None,None,None,None,None,None,cloudflare.cdn.web.prd.q4inc.com.cdn.cloudflar...,None,None,NaN,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,NaN,NaN,NaN,None,None,None,NaN,NaN,NaN,None,None,None,None,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,NaN,None,None,NaN,NaN,NaN,None,None
13065917,A,www.bwpipelines.com.,CNAME,cloudflare.cdn.web.prd.q4inc.com.,60.0,1672534266000,0.034468,1582299107,0,0,ans,None,None,None,None,None,None,cloudflare.cdn.web.prd.q4inc.com.cdn.cloudflar...,None,None,NaN,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,NaN,NaN,NaN,None,None,None,NaN,NaN,NaN,None,None,None,None,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,NaN,None,None,NaN,NaN,NaN,None,None
13065926,AAAA,www.bwpipelines.com.,CNAME,cloudflare.cdn.web.prd.q4inc.com.,60.0,1672534266000,0.000275,1582299107,0,0,ans,None,None,None,None,None,None,cloudflare.cdn.web.prd.q4inc.com.cdn.cloudflar...,None,None,NaN,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,NaN,NaN,NaN,None,None,None,NaN,NaN,NaN,None,None,None,None,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,NaN,None,None,NaN,NaN,NaN,None,None

In [53]:
# Look by AS number
as_records = df[(df["as"] == "23454")] # www.almubasher.com.sa
as_records
# as_records_unique = as_records["query_name"].unique()
# as_records_unique
# df[(df["query_name"] == "www.almubasher.com.sa.")]

Empty DataFrame
Columns: [query_type, query_name, response_type, response_name, response_ttl, timestamp, rtt, worker_id, status_code, ad_flag, section, ip4_address, ip6_address, country, as, as_full, ip_prefix, cname_name, dname_name, mx_address, mx_preference, ns_address, txt_text, ds_key_tag, ds_algorithm, ds_digest_type, ds_digest, dnskey_flags, dnskey_protocol, dnskey_algorithm, dnskey_pk_rsa_n, dnskey_pk_rsa_e, dnskey_pk_rsa_bitsize, dnskey_pk_eccgost_x, dnskey_pk_eccgost_y, dnskey_pk_dsa_t, dnskey_pk_dsa_q, dnskey_pk_dsa_p, dnskey_pk_dsa_g, dnskey_pk_dsa_y, dnskey_pk_eddsa_a, dnskey_pk_wire, nsec_next_domain_name, nsec_owner_rrset_types, nsec3_hash_algorithm, nsec3_flags, nsec3_iterations, nsec3_salt, nsec3_next_domain_name_hash, nsec3_owner_rrset_types, nsec3param_hash_algorithm, nsec3param_flags, nsec3param_iterations, nsec3param_salt, spf_text, soa_mname, soa_rname, soa_serial, soa_refresh, soa_retry, soa_expire, soa_minimum, rrsig_type_covered, rrsig_algorithm, rrsig_labels, rrsig_original_ttl, rrsig_signature_inception, rrsig_signature_expiration, rrsig_key_tag, rrsig_signer_name, rrsig_signature, cds_key_tag, cds_algorithm, cds_digest_type, cds_digest, cdnskey_flags, cdnskey_protocol, cdnskey_algorithm, cdnskey_pk_rsa_n, cdnskey_pk_rsa_e, cdnskey_pk_rsa_bitsize, cdnskey_pk_eccgost_x, cdnskey_pk_eccgost_y, cdnskey_pk_dsa_t, cdnskey_pk_dsa_q, cdnskey_pk_dsa_p, cdnskey_pk_dsa_g, cdnskey_pk_dsa_y, cdnskey_pk_eddsa_a, cdnskey_pk_wire, caa_flags, caa_tag, caa_value, tlsa_usage, tlsa_selector, tlsa_matchtype, tlsa_certdata, ptr_name]
Index: []

In [40]:
# Look by NS records
ns_records = df[(df["response_name"].str.contains('ns.cloudflare.com', na = False))]
# ns_records['domain'] = ns_records['response_name'].str.rstrip('.')
ns_records

,query_type,query_name,response_type,response_name,response_ttl,timestamp,rtt,worker_id,status_code,ad_flag,section,ip4_address,ip6_address,country,as,as_full,ip_prefix,cname_name,dname_name,mx_address,mx_preference,ns_address,txt_text,ds_key_tag,ds_algorithm,ds_digest_type,ds_digest,dnskey_flags,dnskey_protocol,dnskey_algorithm,dnskey_pk_rsa_n,dnskey_pk_rsa_e,dnskey_pk_rsa_bitsize,dnskey_pk_eccgost_x,dnskey_pk_eccgost_y,dnskey_pk_dsa_t,dnskey_pk_dsa_q,dnskey_pk_dsa_p,dnskey_pk_dsa_g,dnskey_pk_dsa_y,dnskey_pk_eddsa_a,dnskey_pk_wire,nsec_next_domain_name,nsec_owner_rrset_types,nsec3_hash_algorithm,nsec3_flags,nsec3_iterations,nsec3_salt,nsec3_next_domain_name_hash,nsec3_owner_rrset_types,nsec3param_hash_algorithm,nsec3param_flags,nsec3param_iterations,nsec3param_salt,spf_text,soa_mname,soa_rname,soa_serial,soa_refresh,soa_retry,soa_expire,soa_minimum,rrsig_type_covered,rrsig_algorithm,rrsig_labels,rrsig_original_ttl,rrsig_signature_inception,rrsig_signature_expiration,rrsig_key_tag,rrsig_signer_name,rrsig_signature,cds_key_tag,cds_algorithm,cds_digest_type,cds_digest,cdnskey_flags,cdnskey_protocol,cdnskey_algorithm,cdnskey_pk_rsa_n,cdnskey_pk_rsa_e,cdnskey_pk_rsa_bitsize,cdnskey_pk_eccgost_x,cdnskey_pk_eccgost_y,cdnskey_pk_dsa_t,cdnskey_pk_dsa_q,cdnskey_pk_dsa_p,cdnskey_pk_dsa_g,cdnskey_pk_dsa_y,cdnskey_pk_eddsa_a,cdnskey_pk_wire,caa_flags,caa_tag,caa_value,tlsa_usage,tlsa_selector,tlsa_matchtype,tlsa_certdata,ptr_name
12052408,A,www.falconsquad.net.,A,ivy.ns.cloudflare.com.,86353.0,1672538789000,0.015755,1582299107,0,0,ans,108.162.192.120,None,US,13335,[13335],108.162.192.0/24,None,None,None,NaN,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,NaN,NaN,NaN,None,None,None,NaN,NaN,NaN,None,None,None,None,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,NaN,None,None,NaN,NaN,NaN,None,None
12052409,A,www.falconsquad.net.,A,ivy.ns.cloudflare.com.,86353.0,1672538789000,0.015755,1582299107,0,0,ans,172.64.32.120,None,JP,13335,[13335],172.64.32.0/24,None,None,None,NaN,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,NaN,NaN,NaN,None,None,None,NaN,NaN,NaN,None,None,None,None,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,NaN,None,None,NaN,NaN,NaN,None,None
12052410,A,www.falconsquad.net.,A,ivy.ns.cloudflare.com.,86353.0,1672538789000,0.015755,1582299107,0,0,ans,173.245.58.120,None,US,13335,[13335],173.245.58.0/24,None,None,None,NaN,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,NaN,NaN,NaN,None,None,None,NaN,NaN,NaN,None,None,None,None,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,NaN,None,None,NaN,NaN,NaN,None,None
12052411,A,www.falconsquad.net.,RRSIG,ivy.ns.cloudflare.com.,86353.0,1672538789000,0.015755,1582299107,0,0,ans,None,None,None,None,None,None,None,None,None,NaN,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,NaN,NaN,NaN,None,None,None,NaN,NaN,NaN,None,None,None,None,NaN,NaN,NaN,NaN,NaN,A,13.0,4.0,86353.0,1.672449e+09,1.672629e+09,34505.0,cloudflare.com.,a378bf0700eef518a8abac064cd34959c0c306d53a78d6...,NaN,NaN,NaN,None,NaN,NaN,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,NaN,None,None,NaN,NaN,NaN,None,None
12052413,AAAA,www.falconsquad.net.,AAAA,ivy.ns.cloudflare.com.,86353.0,1672538789000,0.005360,1582299107,0,0,ans,None,2606:4700:50::adf5:3a78,US,13335,[13335],2606:4700:50::/44,None,None,None,NaN,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,NaN,NaN,NaN,None,None,None,NaN,NaN,NaN,None,None,None,None,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,NaN,None,None,NaN,NaN,NaN,None,None
12052414,AAAA,www.falconsquad.net.,AAAA,ivy.ns.cloudflare.com.,86353.0,1672538789000,0.005360,1582299107,0,0,ans,None,2803:f800:50::6ca2:c078,CR,13335,[13335],2803:f800:50::/45,None,None,None,NaN,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,NaN,NaN,NaN,None,None,None,NaN,NaN,NaN,None,None,None,None,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,NaN,None,None,NaN,NaN,NaN,None,None
12052415,AAAA,www.falconsquad.net.,AAAA,ivy.ns.cloudflare.com.,86353.0,1672538789000,0.005360,1582299107,0,0,ans,None,2a06:98c1:50::ac40:2078,GB,13335,[13335],2a06:98c1:50::/45,None,None,None,NaN,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,NaN,NaN,NaN,None,None,None,NaN,NaN,NaN,None,None,None,None,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,NaN,None,None,NaN,NaN,NaN,None,None
12052416,AAAA,www.falconsquad.net.,RRSIG,ivy.ns.cloudflare.com.,86353.0,1672538789000,0.005360,1582299107,0,0,ans,None,None,None,None,None,None,None,None,None,NaN,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,NaN,NaN,NaN,None,None,None,NaN,NaN,NaN,None,None,None,None,NaN,NaN,NaN,NaN,NaN,AAAA,13.0,4.0,86353.0,1.672449e+09,1.672629e+09,34505.0,cloudflare.com.,34f415eaa6b13f1394a3829210a24d171a5d069be2474c...,NaN,NaN,NaN,None,NaN,NaN,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,NaN,None,None,NaN,NaN,NaN,None,None

In [ ]:
# Process the OpenINTEL data
tranco_a_df = df[df['response_type'] == 'A'] # Filter on DNS response type A
tranco_a_ip4_df = tranco_a_df['ip4_address']  # Get the column we want

tranco_a_ip4_nparray = tranco_a_ip4_df.unique()  # Only grab unique values

tranco_a_df['domain'] = tranco_a_df['response_name'].str.rstrip('.')

tranco_domain_a_df = tranco_a_df[['domain', 'ip4_address']].copy()
unique_tranco_domain_a_df = tranco_domain_a_df.drop_duplicates()
 # Sometimes duplications are found.
# Print count
print('Total IP4 addresses found: %s and unique addresses are %s' %((len(tranco_a_ip4_df), len(tranco_a_ip4_nparray))))

In [ ]:
unique_tranco_domain_a_df.to_csv("../data/tranco-1m/openintel_domain_a_record_2023.csv", index=False)

In [ ]:
# Save ranks of tranco domains in a csv file: tranco_domains_with_rank.csv
import csv

# Load domains and assign ranks
rank_dict = {}
with open("../data/tranco-1m/top-1m.txt", "r", encoding="utf-8") as f, open("../data/tranco-1m/tranco_domains_with_rank.csv", "w") as out:
    writer = csv.writer(out)
    writer.writerow(["domain", "rank"])
    
    for rank, domain in enumerate(f, start=1):  # Auto-assign rank
        domain = domain.strip()
        rank_dict[domain] = str(rank)
        writer.writerow([domain, rank])

In [ ]:
# Find ranks of tranco 1M domains with their A records (IP address/es) and save it into a file.
import csv
import pandas as pd

# 1. Read tranco_domain_a_df that has domain name and ranks: openintel_domain_a_record
# 2. Join it with tranco_domains_with_rank
df1 = pd.read_csv("../data/tranco-1m/tranco_domains_with_rank_2023.csv")
df2 = pd.read_csv("../data/tranco-1m/openintel_domain_a_record_2023.csv")
df3 = df1.merge(df2, how='left', on='domain')

df3.to_csv("../data/tranco-1m/openintel_tranco_resolved_with_rank_2023.csv", index=False)

In [ ]:
# Find the number of matched IP addresses 

# Compare the ip addresses with the protected prefixes using pytricia loop
import pandas as pd
import ipaddress
import pytricia


def build_prefix_trees(prefix_list):
    """Builds two Patricia Tries: one for IPv4 and one for IPv6."""
    pt_v4 = pytricia.PyTricia()
    pt_v6 = pytricia.PyTricia()

    for prefix in prefix_list:
        network = ipaddress.ip_network(prefix)
        if network.version == 4:

            pt_v4[prefix] = True
        else:
            pt_v6[prefix] = True

    return pt_v4, pt_v6

def count_covered_ips(ip_list, pt_v4, pt_v6):
    """Counts how many IPs are covered by the prefixes in the Patricia Tries."""
    count = 0
    for ip in ip_list:
        ip_obj = ipaddress.ip_address(ip)
        if ip_obj.version == 4 and pt_v4.get(ip):
            count += 1
        elif ip_obj.version == 6 and pt_v6.get(ip):
            count += 1

    return count


def get_covered_ips(ip_list, pt_v4, pt_v6):
    """Returns the list of IPs covered by prefixes in the Patricia Trie."""
    covered_ips = []
    for ip in ip_list:
        ip_obj = ipaddress.ip_address(ip)
        if ip_obj.version == 4 and pt_v4.get(ip):
            covered_ips.append(ip)
        elif ip_obj.version == 6 and pt_v6.get(ip):
            covered_ips.append(ip)
#     covered_ips = [ip for ip in ip_list if prefix_tree.get(ip)]
    return covered_ips



# Protected prefixes lists using all five scrubberscovered_count
df = pd.read_csv("../data/customers_prefixes_scrubber_all_2023.csv") 
protected_prefixes = df["prefix"].tolist()

# Openintel list of IP addresses
df = pd.read_csv("../data/tranco-1m/openintel_tranco_resolved_with_rank_2023.csv") 
df_cleaned = df.dropna()

tranco_ip_addresses = df_cleaned["ip4_address"].unique()

# Build separate prefix trees for IPv4 and IPv6
pt_v4, pt_v6 = build_prefix_trees(protected_prefixes)

# Find the number of IPs covered
covered_count = count_covered_ips(tranco_ip_addresses, pt_v4, pt_v6)

# Find the IPs covered
covered_ips = get_covered_ips(tranco_ip_addresses, pt_v4, pt_v6)


# Save covered ips in a .txt file.
with open("../data/tranco-1m/openintel_tranco_scrubber_covered_ip_2023.txt", "w", encoding="utf-8") as f:
    for ip in covered_ips:
        f.write(f"{ip}\n")
print(f"Number of IPs protected by the five scrubber's protected prefixes is: {len(covered_ips)} and IPs saved in openintel_tranco_scrubber_covered_ip_2023.txt")

In [ ]:
# Find ranks of tranco 1M domains with their A records (IP address/es) and save it into a file.
import csv

covered_ips = []
# Parse massdns results
with open("../data/tranco-1m/openintel_tranco_scrubber_covered_ip_2023.txt", "r", encoding="utf-8") as f:
    for line in f:
        ip = line.strip("\n")
        covered_ips.append(ip)
        
# Convert it into a dataframe with column name ipv4_address
df1 = pd.DataFrame(covered_ips, columns=['ip4_address'])

df2 = pd.read_csv("../data/tranco-1m/openintel_tranco_resolved_with_rank_2023.csv")

# df3 = df2.merge(df1, how='inner', on='ip4_address')
        
    
result = df1.merge(df2, on='ip4_address', how='inner')
result.to_csv("../data/tranco-1m/openintel_ip_domains_ranks_2023.csv", index=False)

print("%s number of domains are protected. \n" %len(result))

In [ ]:
result.sort_values("rank", ascending=False)